spring:
	application:
		name: gatewayentretainflix
	cloud:
		loadbalancer:
			ribbon:
				enabled: false
		gateway:
			discovery:
				locator:
					enabled: true
					lowerCaseServiceId: true

eureka:
	instance:
		preferIpAddress: true
	client:
		registerWithEureka: true
		fetchRegistry: true
		serviceUrl:
			defaultZone: http://localhost:8761/eureka/
